# Generated by Django 3.2.1 on 2021-05-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ma_new_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_time', models.TimeField(auto_created=True)),
                ('advisor_name', models.CharField(max_length=20)),
                ('advisor_profie_pic', models.URLField(max_length=20)),
                ('advisor_id', models.IntegerField(max_length=10)),
                ('book_id', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='advisor_photo_url',
            field=models.URLField(max_length=20),
        ),
    ]
