# Generated by Django 3.2.1 on 2021-05-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ma_new_api', '0003_alter_book_calls_advisor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_calls',
            name='book_id',
            field=models.IntegerField(auto_created=True),
        ),
    ]
